before:
  hooks:
    - go mod vendor
    - go mod download
    - sudo apt-get install libpcap-dev

builds:
  - binary: grpcdump
    env:
      - CGO_ENABLED=1
    ldflags:
      - -X github.com/jschwinger233/grpcdump/version.REVISION={{.Commit}}
      - -X github.com/jschwinger233/grpcdump/version.VERSION={{.Env.VERSION}}
      - -X github.com/jschwinger233/grpcdump/version.BUILTAT={{.Date}}
    goos:
      - linux
    goarch:
      - amd64

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

release:
  prerelease: auto

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

